### ISSUE TITLE
Only works in 50mbps on s20 and s21

### ISSUE THREAD

**Issue by ErikBorra** [jlucidar/fpv_viewer_android#11]
25mbps only produces one image, then freezes

**Comment by richardbulger** [comment]
On my Samsung S8 in 50mbps, it freezes for 10-30 seconds, then is fine. Have you tried waiting longer?

**Comment by ErikBorra** [comment]
Yes, tried waiting for more than 20s. On 50mbps it does not even freeze

**Comment by ErikBorra** [comment]
See also #12

**Comment by mavenius** [comment]
This same behavior occurs on my OnePlus 8 Pro (I added this to the pinned issue #12  also.)

**Comment by jlucidar** [comment]
Closing this as all devices info should be added to #12 :)
