### ISSUE TITLE
Oneplus 6

### ISSUE THREAD

**Issue by Sandman224** [jlucidar/fpv_viewer_android#17]
Goggles: V2
Device: Oneplus 6 8gb ram
Android version: 10
Used cable: DELL USB to USBC cable
25 mbit: Works
50 mbit: Works
Latency: ~100ms to +- 300ms
Issue with aspect ratio. App stretches the image to the size of the display.

**Comment by jlucidar** [comment]
Please add this here : https://github.com/fpvout/DigiView-Android/issues/12 :)

**Comment by Sandman224** [comment]
How do i do that sorry kinda noob lol

**Comment by mavenius** [comment]
You can add it as a comment to issue 12.
