### ISSUE TITLE
Add watermark / button to bottom left of the screen

### ISSUE THREAD

**Issue by D3VL-Jack** [jlucidar/fpv_viewer_android#18]
Add a watermark to the bottom right corner of the screen as discussed in dev-chat.
Ideally this would act as a button for the menu of the app, and should be removable by the user if desired.

Assets attached -> [digiview-feed-overlays.zip](https://github.com/fpvout/DigiView-Android/files/6481304/digiview-feed-overlays.zip)
I've added images with and without the text as this may want to be localized in the future.

examples:
![digiview feed#1](https://user-images.githubusercontent.com/21148384/118334876-5b3ba980-b506-11eb-83f3-5ba1e66c44df.jpg)
![digiview feed#5](https://user-images.githubusercontent.com/21148384/118334890-6098f400-b506-11eb-8324-a703c1406dc9.jpg)

**Comment by squshy7** [comment]
@Jack-Rogers just to follow up on my previous suggestion about making it act as a settings button, I was definitely serious about the idea, but it would also be good practice to provide the standard hamburger/3 dots (up for debate which) as well. the watermark being settings is a neat easter egg (at least that was my original vision when I suggested it).

**Comment by D3VL-Jack** [comment]
You're probably right! from a UX point of view, people know what 3 lines means, but less so that they have to click the logo! 

Maybe hamburger top left that hides after 10 seconds if there's no user input and the video is streaming, then If the video stops streaming bring it back into view, and also bring it back if the user touches the screen?

**Comment by richardbulger** [comment]
I personally would rather the video had no overlay at all when viewing it. It's distracting and unaesthetic. Controls/menu button could be shown on tapping the video

**Comment by fichek** [comment]
> I personally would rather the video had no overlay at all when viewing it. It's distracting and unaesthetic. Controls/menu button could be shown on tapping the video

There has to be a bit of branding by default + it's sort of a parody on how Smart Controller does it ;) but will make it easy to remove.

**Comment by jlucidar** [comment]
it's been merged ! thanks @fichek :)
