### ISSUE TITLE
Splash Screens

### ISSUE THREAD

**Issue by D3VL-Jack** [jlucidar/fpv_viewer_android#23]
As a Continuation of #21 - here's the assets and designs for splash screens & screens to show information while not streaming

Icons -> [goggles_icons.zip](https://github.com/fpvout/DigiView-Android/files/6481671/goggles_icons.zip)

Layout suggestions
![demo screen - please connect goggles](https://user-images.githubusercontent.com/21148384/118343516-78ca3c80-b521-11eb-8355-38a11002f388.jpg)
![demo screen - goggles disconnected](https://user-images.githubusercontent.com/21148384/118343517-79fb6980-b521-11eb-8b72-26ce439efa93.jpg)
![demo screen - connection lost](https://user-images.githubusercontent.com/21148384/118343518-7b2c9680-b521-11eb-80fd-9101fe4b4d40.jpg)

**Comment by squshy7** [comment]
Perhaps for "goggles disconnected" put the "slash" in it. This maintains a difference between the "please connect" screen while still also being different from "connection lost" since the color is different.

Thoughts?

**Comment by D3VL-Jack** [comment]
How's this @squshy7 
![demo screen - goggles disconnected - v2](https://user-images.githubusercontent.com/21148384/118373763-58958e80-b5b0-11eb-9a4e-90f8ee79b678.jpg)

Icon -> [goggles_disconnected_white.zip](https://github.com/fpvout/DigiView-Android/files/6487938/goggles_disconnected_white.zip)

**Comment by richardbulger** [comment]
Perhaps remove "dijiview" or move it above, as the pertinent information on the screen looks like a tagline for the brand

**Comment by fichek** [comment]
> Perhaps remove "dijiview" or move it above, as the pertinent information on the screen looks like a tagline for the brand

That's a good point tbh. I don't think we should move "DIGIVIEW" as it's part of the logo, but maybe just use the goggles with no text for these big icons and show the real icon in the little watermark overlay only? @Jack-Rogers ?

**Comment by squshy7** [comment]
I'm ok with this

**Comment by D3VL-Jack** [comment]
+1 to that @fichek, @richardbulger makes an excellent point!

**Comment by fmatt** [comment]
I just replaced the toast messages with this: ![Digiview screen transitions](https://user-images.githubusercontent.com/3429312/118412897-c9b27000-b69c-11eb-887f-a6fbc4052294.png)
Is this in some way like you envision it? (First image shows the splash screen)

**Comment by fichek** [comment]
@fmatt looks good! Wanna open a PR? You can base it off dev branch. We don't have the custom font merged into dev yet so we can add that later.

**Comment by D3VL-Jack** [comment]
The spacing and sizes will definitely need some work, but yes! That's the idea 😁

**Comment by fmatt** [comment]
@fichek i was waiting for PR#31 to be merged, i'm going to do a rebase and prepare the PR tomorrow

**Comment by fichek** [comment]
> @fichek i was waiting for PR#31 to be merged, i'm going to do a rebase and prepare the PR tomorrow

Awesome, the custom font should be merged by then so you can use it, please add a style for these messages to styles.xml 👍 👍

**Comment by jlucidar** [comment]
@fmatt PR #31 is going to be merged asap !
