### ISSUE TITLE
In app logo and text specifications 

### ISSUE THREAD

**Issue by D3VL-Jack** [jlucidar/fpv_viewer_android#24]
The font used for the "DigiView" logo and supporting text is "Gidolinya" 
Source -> https://github.com/larsenwork/Gidole

The DigiView logo and close text should have a letter spacing of 0.22em

Example
![letter spacing example](https://user-images.githubusercontent.com/21148384/118344073-54239400-b524-11eb-9bcc-551bacc92239.jpg)

**Comment by fichek** [comment]
With font and styles.xml added in #31 and a new style for status messages added in #42 I think we covered our use of this font for now so we can close this? @Jack-Rogers

**Comment by D3VL-Jack** [comment]
Agreed!
