### ISSUE TITLE
Tutorial Activity

### ISSUE THREAD

**Issue by SanielDous** [jlucidar/fpv_viewer_android#25]
Adding an activity that demonstrates the use of the app (e.g. the order of switching stuff on and plugging stuff in). Can be shown on first app opening. In my opinion thereby the app becomes more user-friendly and gets a professional look.

If this feature is desirable, I would create a pull request adding such an activity.  Then we should also collect all the information that should be displayed in the short tutorial.

If it's not desirable, just close this issue.

**Comment by jlucidar** [comment]
Hey, nice idea :) I would be waiting for the beta to be ready  before working on this though. UI/UX will probably change quite a bit til then.

**Comment by SanielDous** [comment]
Okay nice :) I will just set up a fork with such an activity and create a WIP pull request. I think this will be relatively independent of the other stuff so it won't mess up with the other UI...

**Comment by jlucidar** [comment]
Sure, make sure your PR is on dev branch :)
