### ISSUE TITLE
Bring Android min SDK down (Android 5.0 - API level 21 would be great)

### ISSUE THREAD

**Issue by rihokirss** [jlucidar/fpv_viewer_android#27]
Is it possible to have an DJI Crystalsky version?
It is running Android 5.1, has nice bright screen and HDMI output. Ideal monitor for outdior use.

**Comment by jlucidar** [comment]
Made the ticket more generic. It should pretty straightforward to lower the min Sdk version. I think targeting android 5+ would be neat. Some people wanted to convert there old phones as auxillary screens.

**Comment by jlucidar** [comment]
Adding this to beta milestone as well.

**Comment by ATKCA** [comment]
Thanks. I have a ton of old devices. 👍

**Comment by jlucidar** [comment]
@ATKCA @rihokirss  Attaching a debugging apk so you guys can tell me if it works on android 5+
[app-debug-android5+.apk.zip](https://github.com/fpvout/DigiView-Android/files/6488411/app-debug-android5%2B.apk.zip)

**Comment by rihokirss** [comment]
Working withot issues on Crystalsky
https://youtu.be/_UFlSxnkAvo

**Comment by jlucidar** [comment]
Cool ! Closing this then :)

**Comment by natemac** [comment]
I get video on my Nexus 7 (2013), but the delay is almost about 2 seconds and the frame rate is very low. No issue on my Pixel 3XL.
