### ISSUE TITLE
One plus 7 plus. Slipping heaps

### ISSUE THREAD

**Issue by SeekaMartin** [jlucidar/fpv_viewer_android#30]
Goggles v1
Phone: oneplus 7 plus
Android 11

Video skips and will no run smooth

https://photos.app.goo.gl/FpoT9uKQhfG2gBcx7

**Comment by jlucidar** [comment]
Please put this in issue #12 🙂 I think other people reported it works ok on their OnePlus 7, so it might be a cable issue.

**Comment by SeekaMartin** [comment]
we used the same cable & goggles on everyone elses phone and it worked seemless. will try again next weekend. I might of opened the app first
