### ISSUE TITLE
Add CI for building the debug apk

### ISSUE THREAD

**Issue by mavenius** [jlucidar/fpv_viewer_android#37]
Having a GitHub action for building the apk will help people like me who don't have android development configured.

PR: https://github.com/fpvout/DigiView-Android/pull/36

**Comment by jlucidar** [comment]
Thanks for the PR :)
Just so you know, we plan to release the app on the play store quickly so people will get updates directly on their phones.

**Comment by mavenius** [comment]
That's cool; this is maybe more selfish than anything. I want to be able to play around to try things out and build a dev version without setting up my machine 🙂
