### ISSUE TITLE
Stretched/cropped video if Android device's screen aspect ratio doesn't match DJI Camera's 4:3 / 16:9

### ISSUE THREAD

**Issue by failsafe-fpv** [jlucidar/fpv_viewer_android#5]
Amazing work btw, latency is so low and app functions really well!

I usually fly with 4:3 mode set in the goggles (to get the widest FOV) but on digiview it seems to stretch the incoming 4:3 stream into 16:9, filling my phone screen but distorting the image.

Thanks,

FailsafeFPV

**Comment by xviews** [comment]
An option for stretch on or off would be good

**Comment by jlucidar** [comment]
Would be great to have this in the beta version !

**Comment by fichek** [comment]
Changed title to be more generic as the same problem exists with 16:9 video on 4:3 screens (see #34). Got a fix for this, will open a PR soon.

**Comment by fichek** [comment]
PR #40 was merged, this will be in the beta release, including zoom in/out as suggested by @xviews 🥳

**Comment by fichek** [comment]
PR #40 was merged, this will be in the beta release, including zoom in/out as suggested by @xviews 🥳
