### ISSUE TITLE
Icon background is a solid colour rather than the gradient

### ISSUE THREAD

**Issue by D3VL-Jack** [jlucidar/fpv_viewer_android#6]
Per title, the required values are 
blue #4776e6 
purple #8e54e9
from bottom left blue to top right purple

**Comment by jlucidar** [comment]
its not on my phone... weird. (its a bit subtle though)

**Comment by D3VL-Jack** [comment]
Interesting, here's a screenshot of my icon, any chance you could take one of yours?
![Digiview Icon](https://user-images.githubusercontent.com/21148384/118216524-950ba200-b46b-11eb-8919-fb57ec4f6963.jpg)

**Comment by jlucidar** [comment]
I can see it have a gradient, don't you ? :p will make it more visible ^^

**Comment by jlucidar** [comment]
A bit better ?
![img](https://github.com/fpvout/DigiView-Android/raw/770d97c8b624ead85ebfcab250777e53622314a7/app/src/main/res/mipmap-xxxhdpi/ic_launcher_alpha_round.png)![img](https://github.com/fpvout/DigiView-Android/raw/770d97c8b624ead85ebfcab250777e53622314a7/app/src/main/res/mipmap-xxxhdpi/ic_launcher_alpha.png)
