### ISSUE TITLE
Otg software trigger

### ISSUE THREAD

**Issue by robertmehrer** [jlucidar/fpv_viewer_android#60]
Explore options for OTG software trigger between usb c devices. This removes the need for special otg cables.

**Comment by jlucidar** [comment]
Do you have any documentation or example that refer to this being possible ? Haven't found anything yet...

**Comment by robertmehrer** [comment]
Something was posted in the group let me see if I can locate it.

**Comment by robertmehrer** [comment]
Don't know if this steers your in the right direction? 

https://www.google.com/amp/s/www.instructables.com/Android-OTG-Development-Interface/%3famp_page=true

**Comment by robertmehrer** [comment]
This actually might be it...


https://developer.android.com/guide/topics/connectivity/usb/host

**Comment by robertmehrer** [comment]
I'm not a dev but I think we have to enumerate the device and then specify an intent, if it's an accessory or host... 

https://developer.android.com/guide/topics/connectivity/usb/accessory



If you want your application to be notified of an attached USB accessory, specify an <intent-filter> and <meta-data> element pair for the android.hardware.usb.action.USB_ACCESSORY_ATTACHED intent in your main activity. The <meta-data> element points to an external XML resource file that declares identifying inf

**Comment by robertmehrer** [comment]
https://community.nxp.com/t5/i-MX-Processors/i-MX6-USB-OTG-mode-switching-without-ID-pin/m-p/241587#M20182


If USB_OTG_ID pin is unconnected, you can control the level by modifying the PUS bits in Pad control register,

Setting PUS to 00, (pull down) -> Host mode

Setting PUS to 01, (pull up)     -> device mode

**Comment by ATKCA** [comment]
https://community.nxp.com/t5/i-MX-Processors/USB-OTG-to-USB-HOST/m-p/237542

https://forum.xda-developers.com/t/neotg-otg-enabler.3556605/

**Comment by jlucidar** [comment]
Ok, I've read through all your links, thank you for investing a bit of time to get those :)

> This actually might be it...
> 
> https://developer.android.com/guide/topics/connectivity/usb/host

This is actually the implementation used in the current version, and we already have `android.hardware.usb.action.USB_ACCESSORY_ATTACHED/DETACHED` events binding working.


> https://community.nxp.com/t5/i-MX-Processors/i-MX6-USB-OTG-mode-switching-without-ID-pin/m-p/241587#M20182
> https://community.nxp.com/t5/i-MX-Processors/USB-OTG-to-USB-HOST/m-p/237542

NXP links show implementation for their embedded linux, but that's not how it works on Android... We don't have access to those low API, nor we want to patch the kernel.

> https://forum.xda-developers.com/t/neotg-otg-enabler.3556605/

This one does require a rooted device. We don't want to go that way too, this would target a very few people in the end.

I'm closing this as this doesn't seems to be possible to force Host mode in Android (except if you want to go the very hacky way). 

Feel free to reopen the issue if you find anything that may solve it in a clean way. 

Thanks !
