### ISSUE TITLE
Localization update

### ISSUE THREAD

**Issue by fichek** [jlucidar/fpv_viewer_android#61]
PRs #57 and #63 introduce [new UI strings](https://github.com/fpvout/DigiView-Android/pull/57/commits/25ab31c87bcaa6496cc08810be5f360b03037e3b#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103) that need to be translated to existing languages (German, Spanish, French and Chinese).

**Comment by Guili123** [comment]
I can help with German translation

**Comment by fichek** [comment]
> I can help with German translation

Cool, thanks, do you know how to work with strings xml files and test them? You can ping me on [Discord](https://discord.gg/UH9jdPNbzK) if you need any help (same username).

**Comment by Guili123** [comment]
> > I can help with German translation
> 
> Cool, thanks, do you know how to work with strings xml files and test them? You can ping me on [Discord](https://discord.gg/UH9jdPNbzK) if you need any help (same username).

Already send you an message on Discord

**Comment by fichek** [comment]
There’s currently just one string left untranslated in the dev branch: `<string name="video_preset_legacy_buffered">Legacy Buffered</string> `, anyone wanna take care of that so we can close this issue?

**Comment by jlucidar** [comment]
> There’s currently just one string left untranslated in the dev branch: `<string name="video_preset_legacy_buffered">Legacy Buffered</string> `, anyone wanna take care of that so we can close this issue?

I wonder if we really want to translate preset names actually... They are not really explicit anyway 😛

**Comment by jlucidar** [comment]
Closing this as it was prior to beta release. We will do another localization update round before v1.0.0 release :)
