### ISSUE TITLE
DigiView not working with Goggles V2 FPV & Vista 01.00.0600

### ISSUE THREAD

**Issue by ostrmik** [jlucidar/fpv_viewer_android#74]
Hi,
DigiView is not working to me unfortunately. It's not reacting on plug / unplug goggles, just showing black screen. Following all recommendations like temp off, 50 Mbps, OTG adapter (both testing devices see flash drive). One is Samsung Galaxy tab S2 Android 7, another one is MI 9T Pro Android 10. Dji Goggles V2 FPV version, firmware 01.00.0600. Please suggest what else I can try to make it working? Are there any known issues with 01.00.0600 version ?

**Comment by Guili123** [comment]
Just to be sure 100%. The OTG adapter need to be plugged into the DJI goggles and not into the smartphone.

**Comment by ostrmik** [comment]
Tried this way and it didn't help. When I plug in smartphone, it asks me how I want to use usb - transfer files, media or just charge. DigiView screen stays black. Do I need root rights on smartphone to allow DigiView to communicate with goggles? Or any permissions? I even tried to enable developer mode but it also didn't help.

**Comment by RiriSe11** [comment]
I'm having a similar issue. The strange thing is after pluging it to my computer and use the browser based method it also worked with my android. Using a USB C Cable with an USB OTG adapter. Phone is Xiaomi Mi 9t pro.

**Comment by jlucidar** [comment]
> Just to be sure 100%. The OTG adapter need to be plugged into the DJI goggles and not into the smartphone.

Nope. the other way around !

**Comment by Guili123** [comment]
> > Just to be sure 100%. The OTG adapter need to be plugged into the DJI goggles and not into the smartphone.
> 
> Nope. the other way around !

Oh my bad... This is Smartphone, not PC... At the PC the OTG adapter need to be at the goggles...
Sorry for the confusion.

**Comment by NiklasVoigt** [comment]
Same here. Caddx + Dji Goggle V2... endless waiting for video..

**Comment by erNail** [comment]
I had the same problem with my Samsung Galaxy S20 FE. I was stuck on "Waiting for Video...". The solution was to restart my phone. I'm using an OTG Adapter and a USB C data cable.

**Comment by jlucidar** [comment]
This seems to be more related to the device used than the goggles or the vista.
Closing this. as @erNail mentionned, rebooting the phone can help (I had to do it on my oneplus 5t a few times, can't find the issue there...)
