### ISSUE TITLE
Port into some other app store in case google play is banned

### ISSUE THREAD

**Issue by DusKing1** [jlucidar/fpv_viewer_android#78]
E.g. China banned Google Play, there are some other app store here like HUAWEI app store or OPPO or Xiaomi etc.

**Comment by D3VL-Jack** [comment]
In that case, the APK can be downloaded from here
https://github.com/fpvout/DigiView-Android/releases/tag/v1.0.0-beta

**Comment by DusKing1** [comment]
Seriously? I'm concerning the distribution not  download link.

**Comment by D3VL-Jack** [comment]
Seriously!

It's a lot of work to maintain a store listing for a handful of users, in this case we'd suggest that they download the official APK from the releases section found here https://github.com/fpvout/DigiView-Android/releases/

It's a possibility that we will add an in app alert when an update is available for those who have not downloaded from the play store so they know they need to update. 

We'll keep our eyes open for anyone else requesting this, and re-evaluate in the future, however, for the minute, this will not be a priority.
