### ISSUE TITLE
Feature request: Stream recording (because SD card in Goggles are not working)

### ISSUE THREAD

**Issue by oderwat** [jlucidar/fpv_viewer_android#84]
I tried out DigiView on a Samsung Tab A7 (WiFi), and it worked really well. But noticed that I could not record the flight to the SD card in the goggles. Is this expected behavior? It showed "no SD" as soon as I connect the cable to the Android device. I thought it is caused by the hardware interface, which may be the same for external storage and the internal SD card. If that is the case, I would love if the app would (optional) automatically store every stream to a storage location on the Android device. Is that possible?

**Comment by MathisEngels** [comment]
The SD card is getting unmounted when you plug the USB cable, it's excepted behavior. 
Also, this feature is already in work (#68 and #79).

**Comment by oderwat** [comment]
Oh. Sorry. I have missed recognizing those PRs. Mostly just checked if there is already an issue with this feature. Sorry for wasting time!

**Comment by YorkyPoo** [comment]
After I tried Digi View out, My googles are unable to recognize the Sd card. Have you had that issue or found a way to reverse it?
