### ISSUE TITLE
Support for FJI FPV drone?

### ISSUE THREAD

**Issue by TheBigFudge** [jlucidar/fpv_viewer_android#90]
Hey guys,
I have seen a video from Mad's Tech about the new Firmware Release for FW 01.02.0000 the DJI Googles V2 and the DJI FPV Drone
[link](https://www.youtube.com/watch?v=qVqYCdT3P64&t=330s)
It added the ability for the dji fpv drone to also connect to the smart controller and D3VL also commented that the DJI Drone is now compatible with Digiview.

So I tried and got it to work with the Windows bat script and the live.fpvout.com website. Unfortunately I can't get it to work with the android app. It recognizes the Google but i could get any video in. The gui indicates that it is still waiting for the video. So is there anything I could try? Sadly I only have one device (Honor 10) to test it on, but this one should meet the Android requirements stated in the readme. And the googles are recognized as well.

Any suggestions what i can try? Or do the Android App need further improvement / updates to also work with the DJI Drone?

**Comment by jlucidar** [comment]
if you can get it to work on Windows, it **should** work on Android too.
All versions of Fpvout software share the same method to retrieve live video from the goggle. please refer to the Readme to see if you missed something during your configuration :)
